### ISSUE TITLE
[Meta] Things to Do - How can you help

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/zeever#24]
- [ ] #24 - START HERE
- [ ] #14 - Subscribe to this topic to get updates on the progress of this project.
- [ ] #1
- [ ] #23 
- [ ] #2 
- [x] #3 
- [x] #4 
- [x] #5 
- [x] #6 
- [ ] #7 - Really looking for the maintainer of a contrib theme to see how your theme works with the Digital Agency Recipe Package. See if it's possible to update your theme (if necessary) to work with the package or if there are things we can do to make the package work better with your theme. 
- [x] #8 
- [ ] #9 - We are using some icons in the Digital Agency Recipe Package. Can you help me use the new Icons API in core to work with this package?
- [x] #10 
- [x] #11 
- [x] #12 
- [x] #13 
- [x] #15 
- [ ] #16 
- [ ] #18 
- [ ] #19 
- [x] #21 
- [x] #22 
- [ ] #25 - We may want to talk about this at office hours sometime soon.
- [x] #26
- [x] #27

Ice box: Things for 2.x? (unless anyone else is inspired to make them happen now)

- [ ] #17 
- [ ] #20
